FROM apache/airflow:2.6.2

USER root

COPY requirements-airflow.txt /requirements-airflow.txt

RUN chown airflow:0 /requirements-airflow.txt

USER airflow

RUN pip install --no-cache-dir -r /requirements-airflow.txt
