from __future__ import annotations

import argparse
from pathlib import Path
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

try:
	from event_fixture_validator import validate_events_file
except ModuleNotFoundError as e:
	raise SystemExit(
		f"Missing dependency while importing the validator: {e}.\n\n"
		"Run this script with the project venv instead:\n"
		"  ./.venv/bin/python scripts/validate_event_generator_fixture.py --mode consistent --file test/fixtures/events/enrollment_events.json\n"
	)


def main(argv: list[str] | None = None) -> int:
	parser = argparse.ArgumentParser(
		description="Validate a synthetic events fixture generated by src/event_generator.py"
	)
	parser.add_argument(
		"--file",
		required=True,
		help="Path to fixture file (JSON array or NDJSON)",
	)
	parser.add_argument(
		"--mode",
		choices=("consistent", "inconsistent"),
		default="consistent",
		help="Validation strictness: consistent checks canonical graph declarations",
	)
	args = parser.parse_args(argv)

	result = validate_events_file(args.file, mode=args.mode)
	if result.is_valid:
		print("OK")
		return 0

	print("INVALID")
	for error in result.errors:
		print(f"- {error}")
	return 2


if __name__ == "__main__":
	raise SystemExit(main())
